jobs:
- job: BuildndPushDev
  displayName: Build and Push (DEV)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'))
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    repoEnv: dev
    containerName: $(DEV_CONTAINER_NAME)
  steps:
  - template: /pipeline/templates/docker-build-push-steps.yml
- job: BuildndPushStage
  displayName: Build and Push (STG)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    repoEnv: stg
    containerName: $(STG_CONTAINER_NAME)
  steps:
  - template: /pipeline/templates/docker-build-push-steps.yml
- job: BuildndPushProd
  displayName: Build and Push (PROD)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    repoEnv: prod
    containerName: $(PROD_CONTAINER_NAME)
  steps:
  - template: /pipeline/templates/docker-build-push-steps.yml