# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev
- release

resources:
- repo: self

variables:
- template: pipeline/variables/vars.yml

stages:
- stage: Build
  displayName: Docker Image
  jobs:
  - job: BuildndPushDev
    displayName: Build and Push (DEV)
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build and Push image to container registry
      inputs:
        command: build
        repository: $(DEV_CONTAINER_NAME)
        dockerfile: '**/Dockerfile'
        containerRegistry: $(CONTAINER_REGISTRY)
        tags: |
          $(CONTAINER_TAG)
        arguments: '--build-arg git_branch=dev .'
    - task: Docker@2
      displayName: Build and Push image to container registry
      inputs:
        command: push
        repository: $(DEV_CONTAINER_NAME)
        containerRegistry: $(CONTAINER_REGISTRY)
        tags: |
          $(CONTAINER_TAG)
  - job: BuildndPushStage
    displayName: Build and Push (STG)
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build and Push image to container registry
      inputs:
        command: buildAndPushProd
        repository: $(STG_CONTAINER_NAME)
        dockerfile: '**/Dockerfile'
        containerRegistry: $(CONTAINER_REGISTRY)
        tags: |
          $(CONTAINER_TAG)
  - job: BuildndPush
    displayName: Build and Push (PROD)
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build and Push image to container registry
      inputs:
        command: buildAndPush
        repository: $(PROD_CONTAINER_NAME)
        dockerfile: '**/Dockerfile'
        containerRegistry: $(CONTAINER_REGISTRY)
        tags: |
          $(CONTAINER_TAG)
- stage: Deploy
  jobs:
  - job: DeployDev
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo dev
  - job: DeployMaster
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo master