# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev
- release

resources:
- repo: self

variables:
- template: pipeline/variables/vars.yml

stages:
- stage: Build
  displayName: Docker Image
  jobs:
  - template: /pipeline/templates/branch-build-push-jobs.yml
- stage: Deploy
  jobs:
  - job: DeployDev
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: kubectlgeneral@3
      inputs:
        k8sService: 'buildrobot'
        subCommand: 'get'
        arguments: 'nodes'
  - job: DeployMaster
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: downloader@1
        inputs:
          k8sService: 'buildrobot'
          hasIstio: false
          hasHelm: false
      - task: kubectlgeneral@3
        inputs:
          k8sService: 'buildrobot'
          subCommand: 'get'
          arguments: 'nodes'
