# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev
- release

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Docker Image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: ecap-service
        dockerfile: '**/Dockerfile'
  - job: Push
    displayName: Push
    dependsOn: Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        command: push
        repository: ecap-service
        dockerfile: '**/Dockerfile'
        containerRegistry: dockerRegistryServiceConnection
        tags: |
          $(tag)
- stage: Deploy
  jobs:
  - job: DeployDev
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo dev
  - job: DeployMaster
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo master