# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev
- release

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: ecap-service
        dockerfile: '**/Dockerfile'
        containerRegistry: dockerRegistryServiceConnection
        tags: |
          $(tag)

  - stage: Deploy
    jobs:
    - job: DeployDev
      pool:
        vmImage: 'ubuntu-16.04'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'))
      steps:
      - script: echo dev
    - job: DeployMaster
      pool:
        vmImage: 'ubuntu-16.04'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
      steps:
      - script: echo master